return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      transparent_background = false,
      flavour = "mocha",
      styles = {
        comments = { "italic" },
        keywords = { "italic" },
        functions = {},
        strings = {},
        variables = {},
      },
      color_overrides = {
        mocha = {
          base = "#0e1116",
          mantle = "#141822",
          crust = "#0a0d12",
          surface0 = "#242b3a",
          surface1 = "#2a3040",
          surface2 = "#32394a",
          overlay0 = "#4a5468",
          overlay1 = "#5b6680",
          overlay2 = "#7c8594",
          subtext0 = "#a7afba",
          subtext1 = "#cfd4dc",
          text = "#e5e7eb",

          blue = "#7c8594",
          teal = "#7c8594",
          peach = "#7c8594",
          green = "#7c8594",
          red = "#7c8594",
          yellow = "#7c8594",

          lavender = "#7c8594",
          mauve = "#7c8594",
          pink = "#7c8594",
          sky = "#7c8594",
          sapphire = "#7c8594",
          maroon = "#7c8594",
          flamingo = "#7c8594",
          rosewater = "#7c8594",
        },
      },
      custom_highlights = function(c)
        return {
          Normal = { bg = c.base, fg = c.text },
          NormalNC = { bg = c.base },
          NormalFloat = { bg = c.mantle },
          FloatBorder = { fg = c.surface2, bg = c.mantle },
          WinSeparator = { fg = c.surface2, bg = c.surface1 },
          VertSplit = { fg = c.surface2, bg = c.surface1 },
          CursorLine = { bg = c.surface1 },
          CursorLineNr = { fg = c.overlay2, bold = true },
          LineNr = { fg = c.overlay1 },
          Visual = { bg = c.surface2 },
          Search = { bg = c.surface2, fg = c.text, bold = true },
          IncSearch = { bg = c.overlay2, fg = c.base, bold = true },
          Comment = { fg = c.overlay2, italic = true },
          Pmenu = { bg = c.mantle },
          PmenuSel = { bg = c.surface1, bold = true },
          StatusLine = { bg = c.mantle, fg = c.subtext0 },
          TabLine = { bg = c.mantle, fg = c.overlay1 },
          TabLineSel = { bg = c.surface0, fg = c.text, bold = true },
          Keyword = { fg = c.text, italic = true },
          Statement = { fg = c.text, italic = true },
          Function = { fg = c.subtext0 },
          String = { fg = c.subtext0 },
          Number = { fg = c.subtext0 },
          Type = { fg = c.text },
          Special = { fg = c.text },
          DiagnosticError = { fg = c.overlay2 },
          DiagnosticWarn = { fg = c.overlay2 },
          DiagnosticInfo = { fg = c.overlay2 },
          DiagnosticHint = { fg = c.overlay2 },
        }
      end,
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
  },
}
