return {
  {
    "ellisonleao/gruvbox.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      terminal_colors = true,
      undercurl = true,
      underline = true,
      bold = true,
      italic = {
        strings = false,
        emphasis = false,
        comments = true,
        operators = false,
        folds = false,
      },
      strikethrough = true,
      invert_selection = false,
      invert_signs = false,
      invert_tabline = false,
      invert_intend_guides = false,
      inverse = true,
      contrast = "soft",
      palette_overrides = {
        light0 = "#f2e5bc",
        light1 = "#ebdbb2",
        light2 = "#d5c4a1",
        light3 = "#bdae93",
        light4 = "#a89984",
        dark0 = "#282828",
        dark1 = "#3c3836",
        dark2 = "#504945",
        dark3 = "#665c54",
        dark4 = "#7c6f64",
        red = "#9d0006",
        green = "#79740e",
        yellow = "#b57614",
        blue = "#076678",
        purple = "#8f3f71",
        aqua = "#427b58",
        orange = "#af3a03",
      },
      overrides = {
        Normal = { bg = "#f2e5bc", fg = "#282828" },
        NormalNC = { bg = "#f2e5bc", fg = "#3c3836" },
        NormalFloat = { bg = "#ebdbb2", fg = "#282828" },
        FloatBorder = { fg = "#bdae93", bg = "#ebdbb2" },
        CursorLine = { bg = "#ebdbb2" },
        CursorLineNr = { fg = "#076678", bg = "#ebdbb2", bold = true },
        LineNr = { fg = "#7c6f64", bg = "#f2e5bc" },
        Visual = { bg = "#d5c4a1" },
        Search = { bg = "#d5c4a1", fg = "#282828", bold = true },
        IncSearch = { bg = "#427b58", fg = "#f2e5bc", bold = true },
        Comment = { fg = "#665c54", italic = true },
        Pmenu = { bg = "#ebdbb2" },
        PmenuSel = { bg = "#d5c4a1", bold = true },
        -- Status line with light backgrounds
        StatusLine = { bg = "#d5c4a1", fg = "#3c3836", bold = true },
        StatusLineNC = { bg = "#ebdbb2", fg = "#7c6f64" },
        -- Tab line
        TabLine = { bg = "#ebdbb2", fg = "#7c6f64" },
        TabLineFill = { bg = "#d5c4a1" },
        TabLineSel = { bg = "#d5c4a1", fg = "#282828", bold = true },
        -- Window separators with light backgrounds
        WinSeparator = { fg = "#d5c4a1", bg = "#f2e5bc" },
        VertSplit = { fg = "#d5c4a1", bg = "#f2e5bc" },
        -- Sign column
        SignColumn = { bg = "#f2e5bc" },
        FoldColumn = { bg = "#f2e5bc", fg = "#7c6f64" },
        -- Syntax highlighting
        Keyword = { fg = "#076678", italic = true },
        Function = { fg = "#427b58" },
        String = { fg = "#79740e" },
        Number = { fg = "#9d0006" },
        Type = { fg = "#076678" },
        Special = { fg = "#8f3f71" },
        Identifier = { fg = "#3c3836" },
        DiagnosticError = { fg = "#9d0006" },
        DiagnosticWarn = { fg = "#af3a03" },
        DiagnosticInfo = { fg = "#076678" },
        DiagnosticHint = { fg = "#427b58" },
        -- Lualine specific - ensure light backgrounds
        lualine_c_normal = { bg = "#d5c4a1", fg = "#3c3836" },
        lualine_b_normal = { bg = "#ebdbb2", fg = "#504945" },
        lualine_a_normal = { bg = "#bdae93", fg = "#282828", bold = true },
      },
      dim_inactive = false,
      transparent_mode = false,
    },
    config = function(_, opts)
      require("gruvbox").setup(opts)
      vim.o.background = "light"
      vim.cmd.colorscheme("gruvbox")
    end,
  },
}
