[theme]
theme = "native"

[icons]
icons = "none"

[[block]]
block = "net"
format = " $device Dwn:$speed_down Up:$speed_up Sgl:$signal_strength "
interval = 5
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "cpu"
interval = 1
format = " CPU $utilization $frequency "
[[block.click]]
button = "left"
cmd = "gnome-system-monitor"

[[block]]
block = "memory"
format = " MEM $mem_used_percents "
interval = 1
warning_mem = 80
critical_mem = 95

[[block]]
block = "temperature"
format = " TEMP $average "
interval = 10
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
format = " FREE $available "
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
format = " BAT $percentage $time $power "
interval = 10
device = "BAT1"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/mic.sh"
interval = 1
format = " MIC $text "
[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/scripts/mic.sh 1"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/updates-pacman.sh"
interval = 60
format = " PKG: $text "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M') "