[theme]
theme = "native"

[icons]
icons = "material-nf"

[theme.overrides]
separator = "  "

[[block]]
block = "net"
format = "󰖩 $speed_down 󰕒 $speed_up"
interval = 5
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "cpu"
interval = 1
format = "󰻠 $utilization"
[[block.click]]
button = "left"
cmd = "gnome-system-monitor"

[[block]]
block = "memory"
format = "󰍛 $mem_used_percents"
interval = 1
warning_mem = 80
critical_mem = 95

[[block]]
block = "temperature"
format = "󱃃 $average"
interval = 10
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
format = "󰋊 $available"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
format = " 󰁺 $percentage "              # Discharging (progresses from 󰁺 to 󰂁)
charging_format = " 󰢜 $percentage "    # Charging
full_format = " 󰁹 "                    # Full
not_charging_format = " 󰂎 $percentage " # Not charging
device = "DisplayDevice"
driver = "upower"
interval = 10

[[block]]
block = "sound"
format = "󰕾 $volume"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/mic.sh"
interval = 1
format = "󰍬 $text"
[[block.click]]
button = "left"
cmd = "~/.config/i3status-rust/scripts/mic.sh 1"

[[block]]
block = "backlight"
format = "󰃞 $brightness"
device = "intel_backlight"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/updates-pacman.sh"
interval = 60
format = "󰏗 $text"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d-%m %H:%M') "