return {
  -- best
  {
    "rebelot/kanagawa.nvim",
    lazy = true,
    event = "VimEnter",
    priority = 1000,
    config = function()
      require("kanagawa").setup({
        compile = false, -- enable compiling the colorscheme
        undercurl = true, -- enable undercurls
        commentStyle = { italic = true },
        functionStyle = { italic = false, bold = false },
        keywordStyle = { italic = false },
        statementStyle = { bold = true },
        typeStyle = {},
        transparent = false, -- do not set background color
        dimInactive = false, -- dim inactive window `:h hl-NormalNC`
        terminalColors = true, -- define vim.g.terminal_color_{0,17}
        colors = {
          -- add/modify theme and palette colors
          palette = {},
          theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
        },
        overrides = function(colors) -- add/modify highlights
          return {}
        end,
        theme = "wave", -- Load "wave" theme when 'background' option is not set
        background = { -- map the value of 'background' option to a theme
          dark = "wave", -- try "dragon" !
          light = "lotus",
        },
      })

      vim.cmd("colorscheme kanagawa")
    end,
  },
  --
  -- vague with kanagawa bg
  -- {
  --   "vague2k/vague.nvim",
  --   config = function()
  --     require("vague").setup({
  --       transparent = false, -- don't set background
  --       style = {
  --         boolean = "bold",
  --         number = "none",
  --         float = "none",
  --         error = "bold",
  --         comments = "italic",
  --         conditionals = "bold", -- Changed to bold for better clarity
  --         functions = "none",
  --         headings = "bold",
  --         operators = "none",
  --         strings = "italic",
  --         variables = "none",
  --         keywords = "bold", -- Changed to bold for better visibility
  --         keyword_return = "italic",
  --         keywords_loop = "bold", -- Changed to bold for better structure visibility
  --         keywords_label = "bold", -- Changed to bold
  --         keywords_exception = "bold", -- Changed to bold for important elements
  --         builtin_constants = "bold",
  --         builtin_functions = "none",
  --         builtin_types = "bold",
  --         builtin_variables = "none",
  --       },
  --       plugins = {
  --         cmp = {
  --           match = "bold",
  --           match_fuzzy = "bold",
  --         },
  --         dashboard = {
  --           footer = "italic",
  --         },
  --         lsp = {
  --           diagnostic_error = "bold",
  --           diagnostic_hint = "italic", -- Changed to italic for differentiation
  --           diagnostic_info = "italic",
  --           diagnostic_warn = "bold",
  --         },
  --         neotest = {
  --           focused = "bold",
  --           adapter_name = "bold",
  --         },
  --         telescope = {
  --           match = "bold",
  --         },
  --       },
  --       colors = {
  --         bg = "#1f1f28", -- Keeping Kanagawa warm dark
  --         fg = "#c8c5bd", -- Keeping the softer than pure white
  --         floatBorder = "#3d3d4f", -- Slightly increased contrast
  --         line = "#2a2a37", -- Kept the same
  --         comment = "#8a889c", -- Increased brightness for better readability
  --         builtin = "#a8d2ca", -- Enhanced contrast
  --         func = "#c59595", -- Brightened for better visibility
  --         string = "#dfc08e", -- Slightly brighter for better contrast
  --         number = "#e3a065", -- Brightened for better visibility
  --         property = "#c0c0d6", -- Enhanced contrast
  --         constant = "#b5b5dd", -- Brighter for better visibility
  --         parameter = "#d0b6d0", -- Brightened for better readability
  --         visual = "#3a3a52", -- Slightly increased contrast
  --         error = "#e66a78", -- Brighter for better visibility
  --         warning = "#f0c070", -- Enhanced contrast
  --         hint = "#8ba3e8", -- Brightened for better visibility
  --         operator = "#aab2c2", -- Enhanced contrast
  --         keyword = "#8da0cb", -- Brightened for clarity
  --         type = "#9ebcb0", -- Enhanced contrast
  --         search = "#465675", -- Brightened for better visibility
  --         plus = "#84b57e", -- Enhanced contrast
  --         delta = "#eac285", -- Brightened for better visibility
  --       },
  --     })
  --     vim.cmd.colorscheme("vague") -- ✅ activate it
  --   end,
  -- },
  --
  -- catppuccin with kanagawa bg
  -- {
  --   "catppuccin/nvim",
  --   name = "catppuccin",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     flavour = "mocha", -- you can try "macchiato" too
  --     transparent_background = false,
  --     background = {
  --       dark = "mocha",
  --       light = "latte",
  --     },
  --     styles = {
  --       comments = { "italic" },
  --       functions = {},
  --       keywords = { "italic" },
  --       strings = {},
  --       variables = {},
  --     },
  --     color_overrides = {
  --       mocha = {
  --         base = "#1f1f28", -- Kanagawa base
  --         mantle = "#1f1f28",
  --         crust = "#191922",
  --       },
  --     },
  --     custom_highlights = function(colors)
  --       return {
  --         Normal = { bg = colors.base },
  --         NormalNC = { bg = colors.base },
  --         FloatBorder = { fg = colors.surface1, bg = colors.base },
  --         Pmenu = { bg = colors.surface0 },
  --       }
  --     end,
  --   },
  --   config = function(_, opts)
  --     require("catppuccin").setup(opts)
  --     vim.cmd.colorscheme("catppuccin")
  --   end,
  -- },
  --
  -- jellybeans with kanagawa bg xD
  -- {
  --   "wtfox/jellybeans.nvim",
  --   lazy = true,
  --   event = "VimEnter",
  --   priority = 1000,
  --   opts = {
  --     style = "dark",
  --     transparent = true,
  --     italics = false,
  --     flat_ui = true,
  --     plugins = {
  --       all = false,
  --       auto = true,
  --     },
  --     on_highlights = function(highlights, colors) end,
  --     on_colors = function(c)
  --       local light_bg = "#ffffff"
  --       local dark_bg = "#1F1F28" -- Kanagawa dark background
  --       c.background = vim.o.background == "light" and light_bg or dark_bg
  --     end,
  --   },
  --   config = function(_, opts)
  --     require("jellybeans").setup(opts)
  --     vim.cmd([[colorscheme jellybeans]]) -- switch from muted to mono
  --   end,
  -- },
  --
  -- kanagawa evolution kanso
  -- {
  --   "webhooked/kanso.nvim",
  --   lazy = true,
  --   event = "VimEnter",
  --   priority = 1000,
  --   config = function()
  --     require("kanso").setup({
  --       compile = false, -- enable compiling the colorscheme
  --       undercurl = true, -- enable undercurls
  --       commentStyle = { italic = true },
  --       functionStyle = {},
  --       keywordStyle = { italic = true },
  --       statementStyle = {},
  --       typeStyle = {},
  --       disableItalics = false,
  --       transparent = false, -- do not set background color
  --       dimInactive = false, -- dim inactive window `:h hl-NormalNC`
  --       terminalColors = true, -- define vim.g.terminal_color_{0,17}
  --       colors = { -- add/modify theme and palette colors
  --         palette = {},
  --         theme = { zen = {}, pearl = {}, ink = {}, all = {} },
  --       },
  --       overrides = function(colors) -- add/modify highlights
  --         return {}
  --       end,
  --       theme = "zen", -- Load "zen" theme
  --       background = { -- map the value of 'background' option to a theme
  --         dark = "zen", -- try "ink" !
  --         light = "pearl",
  --       },
  --     })
  --
  --     vim.cmd("colorscheme kanso")
  --   end,
  -- },
  --
  -- black metal theme
  -- {
  --   "metalelf0/black-metal-theme-neovim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require("black-metal").setup({
  --       theme = "immortal",
  --       -- Can be one of: 'light' | 'dark', or set via vim.o.background
  --       variant = "dark",
  --       -- Use an alternate, darker bg
  --       alt_bg = false,
  --       -- If true, docstrings will be highlighted like strings, otherwise they will be
  --       -- highlighted like comments. Note, behavior is dependent on the language server.
  --       colored_docstrings = true,
  --       -- If true, highlights the {sign,fold} column the same as cursorline
  --       cursorline_gutter = true,
  --       -- If true, highlights the gutter darker than the bg
  --       dark_gutter = false,
  --       -- if true favor treesitter highlights over semantic highlights
  --       favor_treesitter_hl = false,
  --       -- Don't set background of floating windows. Recommended for when using floating
  --       -- windows with borders.
  --       plain_float = false,
  --       -- Show the end-of-buffer character
  --       show_eob = true,
  --       -- If true, enable the vim terminal colors
  --       term_colors = true,
  --       -- Keymap (in normal mode) to toggle between light and dark variants.
  --       toggle_variant_key = nil,
  --       -- Don't set background
  --       transparent = false,
  --
  --       -----DIAGNOSTICS and CODE STYLE-----
  --       --
  --       diagnostics = {
  --         darker = true, -- Darker colors for diagnostic
  --         undercurl = true, -- Use undercurl for diagnostics
  --         background = true, -- Use background color for virtual text
  --       },
  --       -- The following table accepts values the same as the `gui` option for normal
  --       -- highlights. For example, `bold`, `italic`, `underline`, `none`.
  --       code_style = {
  --         comments = "italic",
  --         conditionals = "none",
  --         functions = "none",
  --         keywords = "none",
  --         headings = "bold", -- Markdown headings
  --         operators = "none",
  --         keyword_return = "none",
  --         strings = "none",
  --         variables = "none",
  --       },
  --
  --       -----PLUGINS-----
  --       --
  --       -- The following options allow for more control over some plugin appearances.
  --       plugin = {
  --         lualine = {
  --           -- Bold lualine_a sections
  --           bold = true,
  --           -- Don't set section/component backgrounds. Recommended to not set
  --           -- section/component separators.
  --           plain = false,
  --         },
  --         cmp = { -- works for nvim.cmp and blink.nvim
  --           -- Don't highlight lsp-kind items. Only the current selection will be highlighted.
  --           plain = false,
  --           -- Reverse lsp-kind items' highlights in blink/cmp menu.
  --           reverse = false,
  --         },
  --       },
  --
  --       -- CUSTOM HIGHLIGHTS --
  --       --
  --       -- Override default colors
  --       colors = {},
  --       -- Override highlight groups
  --       highlights = {},
  --     })
  --     require("black-metal").load()
  --   end,
  -- },
  --
  --
  -- third best
  -- {
  --   "bluz71/vim-moonfly-colors",
  --   event = "VimEnter",
  --   name = "moonfly",
  --   priority = 1000,
  --   config = function()
  --     -- Moonfly configuration
  --     vim.g.moonflyCursorColor = true
  --     vim.g.moonflyItalics = true
  --     vim.g.moonflyNormalFloat = true
  --     vim.g.moonflyTerminalColors = true
  --     vim.g.moonflyVirtualTextColor = true
  --     vim.g.moonflyUndercurls = true
  --     vim.g.moonflyVertSplits = true
  --
  --     -- Reduce used colors
  --     vim.g.moonflyWinSeparator = 1
  --
  --     -- Set colorscheme
  --     vim.cmd.colorscheme("moonfly")
  --
  --     -- Override function and search highlights to include italics
  --     vim.api.nvim_set_hl(0, "Function", { italic = true })
  --     vim.api.nvim_set_hl(0, "Search", { italic = true })
  --   end,
  -- },
  --
  -- {
  --   "bluz71/vim-nightfly-colors",
  --   name = "nightfly",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.cmd.colorscheme("nightfly")
  --   end,
  -- },
  --
  -- {
  --   "neanias/everforest-nvim",
  --   event = "VimEnter",
  --   lazy = false,
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   -- Optional; default configuration will be used if setup isn't called.
  --   config = function()
  --     require("everforest").setup({
  --       -- Your config here
  --     })
  --   end,
  -- },
  --
  -- {
  --   "Skardyy/makurai-nvim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("colorscheme makurai")
  --   end,
  -- },
  --
  -- {
  --   "ficcdaf/ashen.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   -- configuration is optional!
  --   init = function()
  --     vim.cmd("colorscheme ashen")
  --   end
  -- },
  --
  -- {
  --   "wnkz/monoglow.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {},
  --   config = function()
  --     vim.cmd([[colorscheme monoglow]])
  --   end,
  -- },
  --
  -- {
  --   "nuvic/flexoki-nvim",
  --   name = "flexoki",
  --   config = function()
  --     require("flexoki").setup({
  --       variant = "auto", -- auto, moon, or dawn
  --       dim_inactive_windows = false,
  --       extend_background_behind_borders = true,
  --
  --       enable = {
  --         terminal = true,
  --         legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
  --         migrations = true,        -- Handle deprecated options automatically
  --       },
  --
  --       styles = {
  --         bold = true,
  --         italic = false,
  --         transparency = false,
  --       },
  --
  --       groups = {
  --         border = "muted",
  --         link = "purple_two",
  --         panel = "surface",
  --
  --         error = "red_one",
  --         hint = "purple_one",
  --         info = "cyan_one",
  --         ok = "green_one",
  --         warn = "orange_one",
  --         note = "blue_one",
  --         todo = "magenta_one",
  --
  --         git_add = "green_one",
  --         git_change = "yellow_one",
  --         git_delete = "red_one",
  --         git_dirty = "yellow_one",
  --         git_ignore = "muted",
  --         git_merge = "purple_one",
  --         git_rename = "blue_one",
  --         git_stage = "purple_one",
  --         git_text = "magenta_one",
  --         git_untracked = "subtle",
  --
  --         h1 = "purple_two",
  --         h2 = "cyan_two",
  --         h3 = "magenta_two",
  --         h4 = "orange_two",
  --         h5 = "blue_two",
  --         h6 = "cyan_two",
  --       },
  --
  --       palette = {
  --         -- Override the builtin palette per variant
  --         -- moon = {
  --         --     base = '#100f0f',
  --         --     overlay = '#1c1b1a',
  --         -- },
  --       },
  --
  --       highlight_groups = {
  --         -- Comment = { fg = "subtle" },
  --         -- VertSplit = { fg = "muted", bg = "muted" },
  --       },
  --
  --       before_highlight = function(group, highlight, palette)
  --         -- Disable all undercurls
  --         -- if highlight.undercurl then
  --         --     highlight.undercurl = false
  --         -- end
  --         --
  --         -- Change palette colour
  --         -- if highlight.fg == palette.blue_two then
  --         --     highlight.fg = palette.cyan_two
  --         -- end
  --       end,
  --     })
  --
  --     -- vim.cmd("colorscheme flexoki")
  --     vim.cmd("colorscheme flexoki-moon")
  --     -- vim.cmd("colorscheme flexoki-dawn")
  --   end,
  -- },
  --
  -- lackluster
  -- {
  --   "slugbyte/lackluster.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   init = function()
  --     -- vim.cmd.colorscheme("lackluster")
  --     vim.cmd.colorscheme("lackluster-hack") -- my favorite
  --     -- vim.cmd.colorscheme("lackluster-mint")
  --   end,
  --   config = function()
  --     local lackluster = require('lackluster')
  --     lackluster.setup({
  --       -- tweak_color allows you to overwrite the default colors in the lackluster theme
  --       tweak_color = {
  --         -- you can set a value to a custom hexcode like' #aaaa77' (hashtag required)
  --         -- or if the value is 'default' or nil it will use lackluster's default color
  --         -- lack = "#aaaa77",
  --         lack = "default",
  --         luster = "default",
  --         orange = "default",
  --         yellow = "default",
  --         green = "default",
  --         blue = "default",
  --         red = "default",
  --         -- WARN: Watchout! messing with grays is probs a bad idea, its very easy to shoot yourself in the foot!
  --         black = "#1F1F28",
  --         -- gray1 = "default",
  --         -- gray2 = "default",
  --         -- gray3 = "default",
  --         -- gray4 = "default",
  --         -- gray5 = "default",
  --         -- gray6 = "default",
  --         -- gray7 = "default",
  --         -- gray8 = "default",
  --         -- gray9 = "default",
  --
  --       },
  --     })
  --   end,
  -- }
  --
  -- flexoki
  -- {
  --   "kepano/flexoki-neovim",
  --   lazy = true,
  --   event = "VimEnter",
  --   priority = 1000,
  --   config = function()
  --     require("lazy").setup({
  --       { 'kepano/flexoki-neovim', name = 'flexoki' }
  --     })
  --     vim.cmd('colorscheme flexoki-dark')
  --   end,
  -- },
  -- {
  --   "CosecSecCot/midnight-desert.nvim",
  --   dependencies = {
  --     "rktjmp/lush.nvim",
  --   },
  --   config = function()
  --     vim.cmd("colorscheme midnight-desert")
  --   end,
  --   -- no setup function required
  -- },
  -- {
  --   "yorumicolors/yorumi.nvim",
  --   event = "VimEnter",
  --   name = "yorumi",
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("colorscheme yorumi")
  --   end,
  -- },
  --
  -- vimbones = light
  -- neobones = dark
  -- {
  --   "mcchrish/zenbones.nvim",
  --   priority = 1000,
  --   lazy = false,
  --   dependencies = {
  --     "rktjmp/lush.nvim"
  --   },
  --   config = function()
  --     vim.cmd.colorscheme("zenbones")
  --   end,
  -- },
  -- {
  --   "nyoom-engineering/oxocarbon.nvim",
  --   lazy = false,          -- make sure we load this during startup if it is your main colorscheme
  --   priority = 1000,       -- make sure to load this before all the other start plugins
  --   opts = {
  --     background = "dark", -- dark or light
  --   },
  --   config = function()
  --     -- load the colorscheme here
  --     vim.cmd.colorscheme("oxocarbon")
  --     vim.opt.background = "dark" -- light | dark
  --   end,
  -- },
  --
  -- {
  --   "blazkowolf/gruber-darker.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     bold = true,
  --     invert = {
  --       signs = false,
  --       tabline = false,
  --       visual = false,
  --     },
  --     italic = {
  --       strings = true,
  --       comments = true,
  --       operators = false,
  --       folds = true,
  --     },
  --     undercurl = true,
  --     underline = true,
  --   },
  --   config = function()
  --     require("gruber-darker").setup({})
  --   end,
  -- },
  --
  -- {
  --   "kevinm6/kurayami.nvim",
  --   event = "VimEnter", -- load plugin on VimEnter or
  --   lazy = false,       --   don't lazy load plugin
  --   priority = 1000,
  --   config = function()
  --     vim.cmd.colorscheme("kurayami") -- this is enough to initialize and load plugin
  --   end,
  --
  --   ---Use this config to override some highlights
  --   -- config = function(_, opts)
  --   ---override highlights passing table
  --   ---@usage
  --   -- opts.override = {
  --   --  Number = { fg = "#015a60" }
  --   -- }
  --   -- require("kurayami").setup(opts)
  --   -- end
  -- },
  -- top 5
  -- {
  --   "Shatur/neovim-ayu",
  --   lazy = false, -- make sure we load this during startup if it is your main colorscheme
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   opts = {
  --     theme = "ayu",
  --   },
  --   config = function()
  --     vim.cmd.colorscheme("ayu")
  --   end,
  -- },
  -- {
  --   "kvrohit/rasmus.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("colorscheme rasmus")
  --   end,
  -- },
  -- github
  -- {
  --   'projekt0n/github-nvim-theme',
  --   lazy = false,    -- make sure we load this during startup if it is your main colorscheme
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     require('github-theme').setup({
  --       -- ...
  --     })
  --
  --     vim.cmd('colorscheme github_dark_default')
  --   end,
  -- }
  -- {
  --   "Mofiqul/adwaita.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.g.adwaita_darker = true -- for darker version
  --     vim.g.adwaita_disable_cursorline = false -- to disable cursorline
  --     vim.g.adwaita_transparent = false -- makes the background transparent
  --     vim.cmd("colorscheme adwaita")
  --   end,
  -- },
  -- --
  -- this also has one of the best light colorschemes
  -- {
  --   "miikanissi/modus-themes.nvim",
  --   priority = 1000,
  --   config = function()
  --     require("modus-themes").setup({
  --       -- Theme comes in two styles `modus_operandi` and `modus_vivendi`
  --       -- `auto` will automatically set style based on background set with vim.o.background
  --       style = "auto",
  --       variant = "default", -- Theme comes in four variants `default`, `tinted`, `deuteranopia`, and `tritanopia`
  --       transparent = false, -- Transparent background (as supported by the terminal)
  --       dim_inactive = false, -- "non-current" windows are dimmed
  --       styles = {
  --         -- Style to be applied to different syntax groups
  --         -- Value is any valid attr-list value for `:help nvim_set_hl`
  --         comments = { italic = true },
  --         keywords = { italic = true },
  --         functions = {},
  --         variables = {},
  --       },
  --
  --       --- You can override specific color groups to use other groups or a hex color
  --       --- function will be called with a ColorScheme table
  --       ---@param colors ColorScheme
  --       on_colors = function(colors) end,
  --
  --       --- You can override specific highlights to use other groups or a hex color
  --       --- function will be called with a Highlights and ColorScheme table
  --       ---@param highlights Highlights
  --       ---@param colors ColorScheme
  --       on_highlights = function(highlights, colors) end,
  --     })
  --   end,
  -- },
  --
  -- {
  --   "Abstract-IDE/Abstract-cs",
  --   priority = 1000,
  --   lazy = false,
  --   config = function()
  --     -- load the colorscheme here
  --     vim.cmd([[colorscheme abscs]])
  --   end,
  -- },
  --
  -- {
  --   "embark-theme/vim",
  --   lazy = false,    -- make sure we load this during startup if it is your main colorscheme
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   event = "VimEnter",
  --   config = function()
  --     vim.cmd.colorscheme("embark")
  --   end,
  -- },
  --
  -- {
  --   "rose-pine/neovim",
  --   lazy = false,
  --   event = "VimEnter",
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     -- load the colorscheme here
  --     vim.cmd([[colorscheme rose-pine]])
  --   end,
  -- },
  --
  -- {
  --   "oxfist/night-owl.nvim",
  --   lazy = false,    -- make sure we load this during startup if it is your main colorscheme
  --   event = "VimEnter",
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     -- load the colorscheme here
  --     vim.cmd.colorscheme("night-owl")
  --   end,
  -- },
  --
  -- tokyo
  -- {
  --   "folke/tokyonight.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {},
  --   config=function ()
  --     vim.cmd[[colorscheme tokyonight-moon]]
  --   end,
  -- },
  --
  -- {
  --   "tiagovla/tokyodark.nvim",
  --   lazy = true,
  --   event = "VimEnter",
  --   priority = 1000,
  --   opts = {
  --     transparent_background = false,
  --     gamma = 1.00,
  --     styles = {
  --       comments = { italic = true },
  --       keywords = { italic = true },
  --       identifiers = { italic = true },
  --       functions = {},
  --       variables = {},
  --     },
  --     on_colors = function(colors)
  --       -- Kanagawa background colors
  --       colors.bg = "#1F1F28"             -- sumiInk1
  --       colors.bg_dark = "#16161D"        -- sumiInk0
  --       colors.bg_float = "#2A2A37"       -- sumiInk2
  --       colors.bg_popup = "#2A2A37"       -- sumiInk2
  --       colors.bg_search = "#2D4F67"      -- waveBlue2
  --       colors.bg_visual = "#223249"      -- waveBlue1
  --       colors.bg_highlight = "#363646"   -- sumiInk3
  --       colors.terminal_black = "#16161D" -- sumiInk0
  --     end,
  --     on_highlights = function(hl, c)
  --       -- Kanagawa-specific highlights
  --       hl.Normal = { bg = c.bg, fg = c.fg }
  --       hl.NormalFloat = { bg = c.bg_float }
  --       hl.LspInlayHint = { bg = c.bg, fg = c.comment }
  --       hl["@module"] = { fg = c.blue }
  --       hl["@property"] = { fg = c.magenta2 }
  --       hl["@variable"] = { fg = c.blue0 }
  --       hl["@lsp.type.variable"] = { fg = c.blue0 }
  --
  --       -- Telescope colors
  --       hl.FloatTitle = { fg = c.blue }
  --       hl.TelescopeBorder = { fg = c.dark5 }
  --       hl.TelescopePreviewBorder = { fg = c.dark5 }
  --       hl.TelescopePreviewTitle = { fg = c.blue }
  --       hl.TelescopePromptBorder = { fg = c.dark5 }
  --       hl.TelescopePromptTitle = { fg = c.blue }
  --       hl.TelescopeResultsBorder = { fg = c.dark5 }
  --       hl.TelescopeResultsTitle = { fg = c.blue }
  --
  --       -- Copilot and Noice
  --       hl.CmpItemKindCopilot = { fg = c.green }
  --       hl.NoiceLspProgressSpinner = { bg = c.bg_float }
  --       hl.NoiceLspProgressClient = { bg = c.bg_float }
  --       hl.NoiceLspProgressTitle = { bg = c.bg_float }
  --       hl.NoiceMini = { bg = c.bg_float }
  --       hl.NoiceCmdlineIconSearch = { fg = c.blue }
  --     end,
  --     terminal_colors = true,
  --   },
  --   config = function(_, opts)
  --     require("tokyodark").setup(opts)
  --     vim.cmd([[colorscheme tokyodark]])
  --   end,
  -- },
  --
  -- {
  --   "loctvl842/monokai-pro.nvim",
  --   dependencies = {
  --     "rktjmp/lush.nvim",
  --   },
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     require("monokai-pro").setup({
  --       transparent_background = false,
  --       terminal_colors = true,
  --       devicons = true, -- highlight the icons of `nvim-web-devicons`
  --       styles = {
  --         comment = { italic = true },
  --         keyword = { italic = true },       -- any other keyword
  --         type = { italic = true },          -- (preferred) int, long, char, etc
  --         storageclass = { italic = true },  -- static, register, volatile, etc
  --         structure = { italic = true },     -- struct, union, enum, etc
  --         parameter = { italic = true },     -- parameter pass in function
  --         annotation = { italic = true },
  --         tag_attribute = { italic = true }, -- attribute of tag in reactjs
  --       },
  --       filter = "pro",                      -- classic | octagon | pro | machine | ristretto | spectrum
  --       -- Enable this will disable filter option
  --       day_night = {
  --         enable = false,            -- turn off by default
  --         day_filter = "pro",        -- classic | octagon | pro | machine | ristretto | spectrum
  --         night_filter = "spectrum", -- classic | octagon | pro | machine | ristretto | spectrum
  --       },
  --       inc_search = "background",   -- underline | background
  --       background_clear = {
  --         -- "float_win",
  --         "toggleterm",
  --         "telescope",
  --         -- "which-key",
  --         "renamer",
  --         "notify",
  --         -- "nvim-tree",
  --         -- "neo-tree",
  --         -- "bufferline", -- better used if background of `neo-tree` or `nvim-tree` is cleared
  --       }, -- "float_win", "toggleterm", "telescope", "which-key", "renamer", "neo-tree", "nvim-tree", "bufferline"
  --       plugins = {
  --         bufferline = {
  --           underline_selected = false,
  --           underline_visible = false,
  --         },
  --         indent_blankline = {
  --           context_highlight = "default", -- default | pro
  --           context_start_underline = false,
  --         },
  --       },
  --     })
  --   end,
  -- },
  --
  -- no-clown-fiesta
  -- {
  --   "aktersnurra/no-clown-fiesta.nvim",
  --   priority = 1000, -- Load colorscheme before other plugins
  --   lazy = false, -- Load during startup
  --   config = function()
  --     require("no-clown-fiesta").setup({
  --       -- Default config
  --       transparent = false, -- Enable transparent background
  --       styles = {
  --         -- Styling choices for syntax elements
  --         comments = {}, -- Style for comments
  --         keywords = {}, -- Style for keywords
  --         functions = {}, -- Style for functions
  --         variables = {}, -- Style for variables
  --         type = {}, -- Style for type annotations
  --         virtual_text = {}, -- Style for virtual text
  --       },
  --       -- Enable/disable specific features
  --       features = {
  --         syntax = true, -- Enable basic syntax highlighting
  --         treesitter = true, -- Enable TreeSitter support
  --         semantic_tokens = true, -- Enable LSP semantic tokens
  --         diagnostic = true, -- Style diagnostic messages
  --       },
  --       -- Optional: Override specific highlight groups
  --       highlights = {
  --         -- Example: override a highlight group
  --         -- Comment = { fg = "#7C7C7C" }
  --       },
  --     })
  --
  --     -- Set the colorscheme
  --     vim.cmd.colorscheme("no-clown-fiesta")
  --   end,
  -- },
  --
  -- {
  --   "matsuuu/pinkmare",
  --   lazy = false,
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("colorscheme pinkmare")
  --   end,
  -- },
}
