return {
  {
    "rebelot/kanagawa.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      compile = false,
      undercurl = true,
      commentStyle = { italic = true },
      functionStyle = {},
      keywordStyle = { italic = true },
      statementStyle = { italic = true },
      typeStyle = {},
      transparent = false,
      dimInactive = false,
      terminalColors = true,
      colors = {
        palette = {
          sumiInk0 = "#16161D",
          sumiInk1 = "#1F1F28",
          sumiInk2 = "#2A2A37",
          sumiInk3 = "#363646",
          sumiInk4 = "#54546D",
          waveBlue1 = "#223249",
          waveBlue2 = "#2D4F67",
          winterGreen = "#2B3328",
          winterYellow = "#49443C",
          winterRed = "#43242B",
          winterBlue = "#252535",
          autumnGreen = "#76946A",
          autumnRed = "#C34043",
          autumnYellow = "#DCA561",
          samuraiRed = "#E82424",
          waveAqua1 = "#6A9589",
          dragonBlue = "#658594",
          fujiWhite = "#DCD7BA",
          oldWhite = "#C8C093",
          oniViolet = "#957FB8",
          lotusPink = "#D27E99",
          waveRed = "#E46876",
          peachRed = "#FF5D62",
          surimiOrange = "#FFA066",
          katanaGray = "#717C7C",
        },
        theme = {
          all = {
            ui = {
              bg_gutter = "none",
            },
          },
        },
      },
      overrides = function(colors)
        local c = colors.palette
        return {
          Normal = { bg = c.sumiInk1, fg = c.fujiWhite },
          NormalFloat = { bg = c.sumiInk0 },
          FloatBorder = { fg = c.waveBlue1, bg = c.sumiInk0 },
          WinSeparator = { fg = c.sumiInk3, bg = c.sumiInk2 },
          VertSplit = { fg = c.sumiInk3, bg = c.sumiInk2 },
          CursorLine = { bg = c.sumiInk2 },
          CursorLineNr = { fg = c.waveAqua1, bold = true },
          LineNr = { fg = c.katanaGray },
          Visual = { bg = c.sumiInk4 },
          Search = { bg = c.waveBlue2, fg = c.fujiWhite, bold = true },
          IncSearch = { bg = c.autumnGreen, fg = c.sumiInk1, bold = true },
          Comment = { fg = c.katanaGray, italic = true },
          Pmenu = { bg = c.sumiInk0 },
          PmenuSel = { bg = c.sumiInk3, bold = true },
          StatusLine = { bg = c.sumiInk0, fg = c.oldWhite },
          TabLine = { bg = c.sumiInk0, fg = c.katanaGray },
          TabLineSel = { bg = c.sumiInk2, fg = c.fujiWhite, bold = true },
          Keyword = { fg = c.oniViolet, italic = true },
          Function = { fg = c.autumnGreen },
          String = { fg = c.autumnYellow },
          Number = { fg = c.samuraiRed },
          Type = { fg = c.waveAqua1 },
          Special = { fg = c.peachRed },
          DiagnosticError = { fg = c.samuraiRed },
          DiagnosticWarn = { fg = c.autumnYellow },
          DiagnosticInfo = { fg = c.dragonBlue },
          DiagnosticHint = { fg = c.waveAqua1 },
        }
      end,
    },
    config = function(_, opts)
      require("kanagawa").setup(opts)
      vim.cmd.colorscheme("kanagawa")
    end,
  },
}
