return {
  -- {
  --   "saghen/blink.cmp",
  --   version = vim.g.lazyvim_blink_main and "*" or "*",
  --   build = vim.g.lazyvim_blink_main and "cargo build --release",
  --   dependencies = {
  --     "rafamadriz/friendly-snippets",
  --     {
  --       "saghen/blink.compat",
  --       optional = true, -- Keep this optional if needed
  --       version = vim.g.lazyvim_blink_main and "*" or "*",
  --     },
  --   },
  --   event = "InsertEnter",
  --   opts = {
  --     completion = {
  --       accept = { auto_brackets = { enabled = true } },
  --       menu = { draw = { treesitter = { "lsp" } } },
  --       documentation = { auto_show = true, auto_show_delay_ms = 200 },
  --     },
  --     sources = {
  --       default = { "lazydev" }, -- Remove compat field
  --       providers = {
  --         lazydev = {
  --           name = "LazyDev",
  --           module = "lazydev.integrations.blink",
  --           score_offset = 100,
  --         },
  --       },
  --     },
  --     keymap = {
  --       ["<Tab>"] = { "select_next" },
  --       ["<S-Tab>"] = { "select_prev" },
  --       ["<C-j>"] = { "select_next" },
  --       ["<C-k>"] = { "select_prev" },
  --       ["<CR>"] = { "accept", "fallback" },
  --     },
  --   },
  --   config = function(_, opts)
  --     -- Validate the configuration for any potential issues before setup
  --     require("blink.cmp").setup(opts)
  --   end,
  -- },
  -- {
  --   "hrsh7th/nvim-cmp",
  --   event = "InsertEnter",
  --   opts = {
  --     mapping = {
  --       ["<CR>"] = require("cmp").mapping({
  --         i = function(fallback)
  --           if require("cmp").visible() then
  --             require("cmp").confirm({ select = true })
  --           else
  --             fallback()
  --           end
  --         end,
  --       }),
  --     },
  --   },
  -- },
}
