return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      transparent_background = false,
      flavour = "mocha",
      styles = {
        comments = { "italic" },
        keywords = { "italic" },
        functions = {},
        strings = {},
        variables = {},
      },
      color_overrides = {
        mocha = {
          base = "#0D0E11",
          mantle = "#06060b",
          crust = "#030308",
          surface0 = "#0e0e16",
          surface1 = "#14141e",
          surface2 = "#1c1c28",
          overlay0 = "#383850",
          overlay1 = "#5a5a78",
          overlay2 = "#7070a0",
          subtext0 = "#9090aa",
          subtext1 = "#b0b0c8",
          text = "#dcdce8",

          blue = "#88b4e8",
          teal = "#6dd4bc",
          peach = "#e8a87c",
          green = "#d4c46a",
          red = "#e88a97",
          yellow = "#e8d080",

          lavender = "#88b4e8",
          mauve = "#88b4e8",
          pink = "#88b4e8",
          sky = "#88b4e8",
          sapphire = "#88b4e8",
          maroon = "#e88a97",
          flamingo = "#e88a97",
          rosewater = "#c8a8e8",
        },
      },
      custom_highlights = function(c)
        return {
          Normal = { bg = c.base, fg = c.text },
          NormalNC = { bg = c.base },
          NormalFloat = { bg = c.mantle },
          FloatBorder = { fg = c.surface2, bg = c.mantle },
          WinSeparator = { fg = c.surface1, bg = c.surface1 },
          VertSplit = { fg = c.surface1, bg = c.surface1 },
          CursorLine = { bg = c.surface1 },
          CursorLineNr = { fg = c.blue, bold = true },
          LineNr = { fg = c.overlay1 },
          Visual = { bg = c.surface2 },
          Search = { bg = c.surface2, fg = c.text, bold = true },
          IncSearch = { bg = c.blue, fg = c.base, bold = true },
          Comment = { fg = c.subtext0, italic = true },
          Pmenu = { bg = c.mantle },
          PmenuSel = { bg = c.surface1, bold = true },
          PmenuThumb = { bg = c.surface2 },
          StatusLine = { bg = c.mantle, fg = c.subtext0 },
          TabLineFill = { bg = c.crust },
          TabLine = { bg = c.mantle, fg = c.overlay1 },
          TabLineSel = { bg = c.surface0, fg = c.text, bold = true },
          SignColumn = { bg = c.base },
          FoldColumn = { bg = c.base },
          Keyword = { fg = c.blue, italic = true },
          Statement = { fg = c.blue, italic = true },
          Function = { fg = c.teal },
          String = { fg = c.green },
          Number = { fg = c.peach },
          Boolean = { fg = c.peach },
          Constant = { fg = c.peach },
          Type = { fg = c.blue },
          PreProc = { fg = c.blue },
          Special = { fg = c.text },
          Operator = { fg = c.text },
          Identifier = { fg = c.text },
          ["@keyword"] = { fg = c.blue, italic = true },
          ["@function"] = { fg = c.teal },
          ["@string"] = { fg = c.green },
          ["@number"] = { fg = c.peach },
          ["@type"] = { fg = c.blue },
          ["@variable"] = { fg = c.rosewater },
          DiagnosticError = { fg = c.red },
          DiagnosticWarn = { fg = c.yellow },
          DiagnosticInfo = { fg = c.blue },
          DiagnosticHint = { fg = c.teal },
        }
      end,
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin")
    end,
  },
}
